### ISSUE TITLE
Simple Example Fails

### ISSUE THREAD

**Issue by tapickell** [FredericHeem/rabbitmq-pubsub#1]
trying to test this with a simple demo like what is in the readme
But I get a Stacktrace.
Is this missing something from Babel like polyfill?

```
2016-07-27T01:32:00.245Z - info: [publisher] Publisher options: { exchange: 'message-bus',
  type: 'fanout',
  url: 'amqp://localhost' }
2016-07-27T01:32:00.248Z - info: [subscriber] Subscriber options: { exchange: 'message-bus',
  queueName: 'kraken',
  routingKeys: [ 'kraken' ],
  type: 'topic',
  url: 'amqp://localhost' }
/Users/Me/code/amqp-fanout-pubsub-test/node_modules/rabbitmq-pubsub/build/subscriber.js:47
            return _regeneratorRuntime.async(function start$(context$2$0) {
                                      ^

TypeError: Cannot read property 'async' of undefined
    at Subscriber.start (/Users/Me/code/amqp-fanout-pubsub-test/node_modules/rabbitmq-pubsub/build/subscriber.js:47:39)
    at Object.<anonymous> (/Users/Me/code/amqp-fanout-pubsub-test/index.js:43:12)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.runMain (module.js:575:10)
    at run (node.js:348:7)
    at startup (node.js:140:9)
    at node.js:463:3
```

**Comment by FredericHeem** [comment]
This lib is using async/await so the babel runtime is needed. It really depends on whether babel 5 or 6 is used in your project.

**Comment by tapickell** [comment]
So any project using this will need to require Babel on it's own? 
What specific Babel modules are needed for this?

**Comment by FredericHeem** [comment]
Once you play with async/wait, you cannot go back to callback or promises. So yes, right now, projects that depend on this lib need babel.
Are you using babel 5 or 6 or nothing at all ?

**Comment by tapickell** [comment]
Nothing, we don't require babel for this project.
